✨ Rename `Treatment` to `Perturbation`, add `Donor` registry, improve `GeneticPerturbationSystem` typing
laminlabs/wetlab pull request #80
Opened 2024-11-29 16:47 UTC by Zethson

Fixes https://github.com/laminlabs/wetlab/issues/77
Fixes https://github.com/laminlabs/wetlab/issues/78
Fixes https://github.com/laminlabs/wetlab/issues/79

- Improves typing for GeneticPerturbationSystem by properly referencing the Literal type
- Renames all treatments to perturbations
- Adds a donor schema that also covers all hubmap instance requirements

2024-12-04 14:28 UTC, sunnyosun requested changes

2024-12-04 14:28 UTC, sunnyosun commented on wetlab/migrations/0028_remove_combinationtreatment_artifacts_and_more.py
I think this migration files drops a lot of data, see all the drop field operations and recreate them.

Renaming is not easy, I think you need to talk to claude and ask for the raw sql commands that actually transfers data.

2024-12-05 04:30 UTC, falexwolf commented
Nice!

2024-12-05 04:31 UTC, falexwolf commented on wetlab/migrations/0028_remove_combinationtreatment_artifacts_and_more.py
Yes, beware of migrating data before dropping tables.

2024-12-05 04:33 UTC, falexwolf commented on wetlab/migrations/0028_remove_combinationtreatment_artifacts_and_more.py
But maybe in this case it's alright because nobody has data in these tables yet?

2024-12-05 08:42 UTC, Zethson commented on wetlab/migrations/0028_remove_combinationtreatment_artifacts_and_more.py
No, it’s not all right because I have recommended wetlab to people, and there might be users relying on it. Anyway, as I mentioned in a DM to Sunny, I recreated the migration script after her approval, and now no tables are being dropped.

2024-12-05 08:53 UTC, sunnyosun approved these changes

2024-12-05 09:07 UTC, merged